{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tiaki-control.fullname" . }}
  labels:
    {{- include "tiaki-control.labels" . | nindent 4 }}
type: Opaque
data:
  admin-token: {{ .Values.config.adminToken | b64enc | quote }}
  database-url: {{ include "tiaki-control.databaseUrl" . | b64enc | quote }}
  {{- if .Values.config.smtp.user }}
  smtp-user: {{ .Values.config.smtp.user | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.smtp.password }}
  smtp-password: {{ .Values.config.smtp.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.anthropic.apiKey }}
  anthropic-api-key: {{ .Values.config.anthropic.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.github.token }}
  github-token: {{ .Values.config.github.token | b64enc | quote }}
  {{- end }}
{{- end }}
