blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/itlabs-gmbh/tiaki/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Issue
    url: https://github.com/itlabs-gmbh/tiaki/security/advisories/new
    about: Report a security vulnerability privately
