{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tiaki-agent.fullname" . }}
  labels:
    {{- include "tiaki-agent.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.config.apiKey | b64enc | quote }}
  {{- if .Values.registry.username }}
  registry-username: {{ .Values.registry.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.registry.password }}
  registry-password: {{ .Values.registry.password | b64enc | quote }}
  {{- end }}
{{- end }}
