FROM golang:1.26-alpine AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o tiaki-agent-k8s ./cmd/k8s

FROM ghcr.io/aquasecurity/trivy:latest AS trivy-bin

FROM alpine:3.23
RUN apk upgrade --no-cache && apk add --no-cache ca-certificates
COPY --from=builder /build/tiaki-agent-k8s /tiaki-agent-k8s
COPY --from=trivy-bin /usr/local/bin/trivy /usr/local/bin/trivy
ENTRYPOINT ["/tiaki-agent-k8s"]
