import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "Introduction",
    },
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        "getting-started/installation",
        "getting-started/first-agent",
        "getting-started/dashboard-tour",
      ],
    },
    {
      type: "category",
      label: "Configuration",
      items: [
        "configuration/control-plane",
        "configuration/agent-docker",
        "configuration/agent-kubernetes",
        "configuration/private-registries",
        "configuration/notifications",
        "configuration/security-scanning",
        "configuration/git-integration",
      ],
    },
    {
      type: "category",
      label: "Deployment",
      items: [
        "deployment/production",
        "deployment/kubernetes",
        "deployment/upgrades",
      ],
    },
    {
      type: "category",
      label: "Developer Guide",
      items: [
        "developer/architecture",
        "developer/local-development",
        "developer/contributing",
        "developer/testing",
      ],
    },
    {
      type: "category",
      label: "Help",
      items: ["help/troubleshooting", "help/faq"],
    },
  ],
  apiSidebar: [
    {
      type: "doc",
      id: "api/index",
      label: "Overview",
    },
    {
      type: "autogenerated",
      dirName: "api",
    },
  ],
};

export default sidebars;
